[tools]
tuist = "4.20.0
[1m[33m
The following warnings need attention:[0m[1m[0m
[33m · The method used to install this version of Tuist is deprecated and will be deleted soon.
Please, uninstall it by running:

    curl -Ls https://uninstall.tuist.io | bash

And follow the new installation instructions at https://docs.tuist.io/documentation/tuist/installation

Read more about the rationale at https://tuist.io/blog/2023/12/15/rtx-default/[0m"
